### ISSUE TITLE
1.20.0

### ISSUE THREAD

**Issue by DannyPenton236** [lihaochen910/ClipStudioPaintForMacOS-Reverse-Engineering-Notes#1]
Hello. Any plan to update the patch for 1.20.0?

**Comment by lihaochen910** [comment]
Version 1.20.0 takes some time to analyze, because there are some changes in the verification logic of this version.

**Comment by DannyPenton236** [comment]
Ok. Thanks

**Comment by lihaochen910** [comment]
see release [1.12.0](https://github.com/lihaochen910/ClipStudioPaintForMacOS-Reverse-Engineering-Notes/releases/tag/v1.12.0)

**Comment by DannyPenton236** [comment]
Oh I am going to try it out. Hopefully the Companion mode work as well. Thanks

**Comment by serendipity-pink** [comment]
官网的最新版本已经原生支持m1了，用了这个补丁后成了转译。咨询一下，能原生支持m1吗。我不是做mac开发的，不清楚具体细节。

**Comment by lihaochen910** [comment]
@serendipity-pink 目前暂时没有计划去搞arm64那部分。也许之后找到更好的方式去破解的时候再去弄arm64那部分

**Comment by DannyPenton236** [comment]
There is a new update. 1.12.3. Any plan updating?

**Comment by lihaochen910** [comment]
@DannyPenton236 [updated](https://github.com/lihaochen910/ClipStudioPaintForMacOS-Reverse-Engineering-Notes/releases/tag/v1.12.3).
