### ISSUE TITLE
Clip Studio Paint 2.0.6 doesnt boot up after patching

### ISSUE THREAD

**Issue by ThatKoza** [lihaochen910/ClipStudioPaintForMacOS-Reverse-Engineering-Notes#13]
this is the earliest 2.0 version i could find, so i assume it should've worked fine. when booting up the program, it doesnt start up and after exiting it, gives error with "clip studio quit unexpectedly". would also to be nice to release patch for 3rd version

**Comment by lihaochen910** [comment]
2.0.6 patch released.
