### ISSUE TITLE
Bypassing Experience Selection

### ISSUE THREAD

**Issue by cagednoodle** [lihaochen910/ClipStudioPaintForMacOS-Reverse-Engineering-Notes#2]
Hi sorry, are the details as to how to know if this has been installed correctly. When I start Clip Studio Paint it still asks me to select which trial id like to use. Unless I am mistaken and this is not a crack .

Thank you

**Comment by lihaochen910** [comment]
If you encounter a prompt to select the trial version when you open csp, it should be the reason why you did not replace the file correctly, check whether you have correctly replaced "/Applications/CLIP STUDIO 1.5/App/CLIP STUDIO PAINT.app/Contents/MacOS /CLIP STUDIO PAINT" this file.

**Comment by cagednoodle** [comment]
Hi Thank you, it worked on older version as I tried on 12.1. Thanks again version 10 is fine for now. Thank you for your time
